platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: 5b44bd954693937ddd07ee6c9e113923bc620aed
inputs:
  - name: git-master
    path: src
params:
  CF_API: https://api.cloud.service.gov.uk
  CF_USERNAME: ((paas-username))
  CF_PASSWORD: ((paas-password))
  CF_ORG: govuk_development
  SENTRY_DSN: https://((sentry-dsn))
  SECRET_KEY_BASE:
  CF_STARTUP_TIMEOUT:
  CF_SPACE:
  HOSTNAME:
  INSTANCES:
  BASIC_AUTH_PASSWORD:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ERROR_PAGES_BUCKET_NAME:
  AWS_REGION: eu-west-2
  DATA_EXPORT_BASIC_AUTH_USERNAME:
  DATA_EXPORT_BASIC_AUTH_PASSWORD:
  GA_VIEW_ID: UA-43115970-1
  GA_CROSS_DOMAIN_ID: UA-145652997-1
run:
  dir: src
  path: sh
  args:
    - '-c'
    - |
      set -eu

      cf api "$CF_API"
      cf auth
      cf t -o "$CF_ORG" -s "$CF_SPACE"
      cf v3-create-app govuk-coronavirus-find-support || true
      cf v3-apply-manifest -f manifest.yml
      cf set-env govuk-coronavirus-find-support CF_STARTUP_TIMEOUT "$CF_STARTUP_TIMEOUT"

      cf scale -i "$INSTANCES" govuk-coronavirus-find-support

      cf set-env govuk-coronavirus-find-support AWS_ASSETS_BUCKET_NAME "$AWS_ASSETS_BUCKET_NAME"
      if [[ "${REQUIRE_BASIC_AUTH:-}" = "true" ]]; then
        cf set-env govuk-coronavirus-find-support REQUIRE_BASIC_AUTH "$REQUIRE_BASIC_AUTH"
      fi
      cf set-env govuk-coronavirus-find-support BASIC_AUTH_PASSWORD "$BASIC_AUTH_PASSWORD"
      cf set-env govuk-coronavirus-find-support DATA_EXPORT_BASIC_AUTH_USERNAME "$DATA_EXPORT_BASIC_AUTH_USERNAME"
      cf set-env govuk-coronavirus-find-support DATA_EXPORT_BASIC_AUTH_PASSWORD "$DATA_EXPORT_BASIC_AUTH_PASSWORD"
      cf set-env govuk-coronavirus-find-support SENTRY_DSN "$SENTRY_DSN"
      cf set-env govuk-coronavirus-find-support SENTRY_CURRENT_ENV "$CF_SPACE"
      cf set-env govuk-coronavirus-find-support GA_VIEW_ID "$GA_VIEW_ID"
      cf set-env govuk-coronavirus-find-support GA_CROSS_DOMAIN_ID "$GA_CROSS_DOMAIN_ID"
      cf set-env govuk-coronavirus-find-support AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
      cf set-env govuk-coronavirus-find-support AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
      cf set-env govuk-coronavirus-find-support SECRET_KEY_BASE "$SECRET_KEY_BASE"
      cf set-env govuk-coronavirus-find-support AWS_ERROR_PAGES_BUCKET_NAME "$AWS_ERROR_PAGES_BUCKET_NAME"
      cf set-env govuk-coronavirus-find-support AWS_REGION "$AWS_REGION"

      cf v3-zdt-push govuk-coronavirus-find-support --wait-for-deploy-complete --no-route
      cf map-route govuk-coronavirus-find-support cloudapps.digital --hostname "$HOSTNAME"
