platform: linux
image: tests-image
inputs:
  - name: git-master
params:
  TEST_URL:
run:
  dir: git-master
  path: bash
  args:
    - -c
    - |
      set -eu
      service postgresql start
      su - postgres -c "psql -c \"create role root with createdb login password 'password';\""
      export DATABASE_URL="postgres://root:password@localhost:5432/coronavirus_find_support_form_development"
      bundle install
      bundle exec rails db:setup
      bundle exec rails db:migrate
      TEST_URL="$TEST_URL" bundle exec rspec spec/features
